# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interview.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(931, 662)
        Form.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 127);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 30, 861, 61))
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 18pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(190, 120, 151, 51))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(190, 210, 131, 51))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(190, 300, 131, 51))
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(190, 390, 141, 51))
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.textinterview = QtWidgets.QLineEdit(Form)
        self.textinterview.setGeometry(QtCore.QRect(432, 121, 141, 51))
        self.textinterview.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.textinterview.setObjectName("textinterview")
        self.textcgpa = QtWidgets.QLineEdit(Form)
        self.textcgpa.setGeometry(QtCore.QRect(430, 210, 141, 51))
        self.textcgpa.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.textcgpa.setObjectName("textcgpa")
        self.textwritten = QtWidgets.QLineEdit(Form)
        self.textwritten.setGeometry(QtCore.QRect(430, 300, 141, 51))
        self.textwritten.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.textwritten.setObjectName("textwritten")
        self.textaptitude = QtWidgets.QLineEdit(Form)
        self.textaptitude.setGeometry(QtCore.QRect(430, 391, 141, 51))
        self.textaptitude.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.textaptitude.setObjectName("textaptitude")
        self.buttonpredict = QtWidgets.QPushButton(Form)
        self.buttonpredict.setGeometry(QtCore.QRect(350, 480, 131, 61))
        self.buttonpredict.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.buttonpredict.setObjectName("buttonpredict")
        self.labelresult = QtWidgets.QLabel(Form)
        self.labelresult.setGeometry(QtCore.QRect(290, 580, 241, 51))
        self.labelresult.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelresult.setText("")
        self.labelresult.setObjectName("labelresult")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "  PREDICT WHETHER A PERSON IS HIRED OR NOT"))
        self.label_2.setText(_translate("Form", "   Interview"))
        self.label_3.setText(_translate("Form", "      CGPA"))
        self.label_4.setText(_translate("Form", "   Written"))
        self.label_5.setText(_translate("Form", "    Aptitude"))
        self.buttonpredict.setText(_translate("Form", "PREDICT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
